site_name: 喵喵基础算法
site_description: 个人学习知识库

theme:
  name: material
  custom_dir: overrides
  palette:
    primary: teal
    accent: green
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - navigation.instant


extra_css:
  - stylesheets/custom.css 

nav:
  - 首页: index.md
  - 基础算法:
    - 编程语言:
      - Python: python.md
      - C语言: c.md
      - C++: cpp.md
    - 数学技巧:
      - 经典数学题: math-problem.md
      - 简化计算: simplify-computation.md
      - 数学公式: math-formula.md

    - 算法:
      - 字符串: string.md
      - 排序: sort.md
      - 枚举: enum.md
      - 二分查找: binary-search.md
      - 时间复杂度: Time Complexity.md
      - 高精度算法: high-precision.md
      - 动态规划: Dynamic Programming.md
      - 广度优先搜索: Breadth-First Search.md
      - 深度优先搜索: Depth-First Search.md
      - 贪心算法: Greedy Algorithm.md
      - STL容器: standard template library.md
      - 前缀和与差分: prefix-sum.md
      - 树状数组: fenwick-tree.md
      - 线段树: segment-tree.md
      - 滑动窗口: sliding-window.md
  - 数据结构:

    - 线性表: linear-list.md  # 注释
    - 二叉树: binary-tree.md   
    - 栈: stack.md   
    - 队列: queue.md   
    - 堆: heap.md   
    - 集合: set.md          # 注释  
    - 图的基本应用: graph.md          # 注释  
  - 个人学习分享: route.md
 

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css  
extra_css:
  - stylesheets/custom.css
  